name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # Tarvitaan releasen luomiseen ja tiedostojen lataamiseen
  packages: write  # Jos käytät packages
  id-token: write  # Jos tarvitset OIDC-tokenia

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          zip -r spot_scheduler.zip custom_components/spot_scheduler

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: spot_scheduler.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
